# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/ecommerce_db?serverTimezone=UTC
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
